OBJS   = GP.o polys.o
TARGET = polys
CFLAGS = -Wall -Wextra
LDFLAGS = `libusb-config --libs` -lm

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJS)

all: $(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)

.PHONY: clean
